import os

from SCons.Environment import Environment
from build_scripts.utility import GlobRecursive, FindIndex, IsFileName


Import('TARGET_ENVIRONMENT')
TARGET_ENVIRONMENT: Environment

env = TARGET_ENVIRONMENT.Clone()
env.Append(
    LINKFLAGS = [
        '-Wl,-T', env.File('linker.ld').srcnode().path,
        '-Wl,-Map=' + env.File('kernel.map').path
    ],
    CPPPATH = [ 
        env.Dir('.').srcnode(),
        env['PROJECTDIR'].Dir('src/libs')
    ],
    ASFLAGS = [ '-I', env.Dir('.').srcnode(), '-I', env.Dir('arch/i686').srcnode(), '-f', 'elf' ]
)

def flatten(nested):
    flat = []
    for group in nested:
        if isinstance(group, list):
            flat.extend(group)
        else:
            flat.append(group)
    return flat

c_sources = flatten(GlobRecursive(env, '*.c'))
cpp_sources = flatten(GlobRecursive(env, '*.cpp'))
asm_sources = flatten(GlobRecursive(env, '*.asm'))

# Prefer C entrypoint and exclude legacy main.asm to avoid duplicate main.o
asm_sources = [node for node in asm_sources if not IsFileName(node, 'main.asm') and not IsFileName(node, 'isrs_gen.asm')]

sources = c_sources + cpp_sources + asm_sources

objects = env.Object(sources)
obj_crti = objects.pop(FindIndex(objects, lambda item: IsFileName(item, 'crti.o')))
obj_crtn = objects.pop(FindIndex(objects, lambda item: IsFileName(item, 'crtn.o')))

Import('libcore')
Import('libstring')

static_libs = [
    libcore,
    libstring,
]

objects = [
    obj_crti,
    os.path.join(env["TOOLCHAIN_LIBGCC"], 'crtbegin.o'),
    *objects,
    *static_libs,
    os.path.join(env["TOOLCHAIN_LIBGCC"], 'crtend.o'),
    obj_crtn
]

kernel = env.Program('kernel.elf', objects)

kernel_stripped = env.Command('kernel-stripped.elf', kernel, '$STRIP -o $TARGET $SOURCE')
env.Default(kernel_stripped)

Export('kernel')
Export('kernel_stripped')