from SCons.Environment import Environment
from build_scripts.utility import GlobRecursive

Import('TARGET_ENVIRONMENT')
TARGET_ENVIRONMENT: Environment

env = TARGET_ENVIRONMENT.Clone()

env.Append(
    CPPPATH=[
        env.Dir('.').srcnode(),
    ],
)

sources = GlobRecursive(env, '*.c')

objects = env.Object(sources)

libstring = env.Library('string', objects)

Export('libstring')
